"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import Link from "next/link";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { FileText, Plus, Zap, ChevronLeft, ChevronRight, Search, Download, X, Loader2 } from "lucide-react";

const statusColors: Record<string, string> = {
  DRAFT: "bg-gray-100 text-gray-700",
  PENDING_APPROVAL: "bg-yellow-100 text-yellow-700",
  APPROVED: "bg-blue-100 text-blue-700",
  SENT: "bg-purple-100 text-purple-700",
  CONFIRMED: "bg-green-100 text-green-700",
  PARTIALLY_RECEIVED: "bg-orange-100 text-orange-700",
  RECEIVED: "bg-green-200 text-green-800",
  CANCELLED: "bg-red-100 text-red-700",
  CLOSED: "bg-gray-200 text-gray-600",
};

const PO_STATUSES = [
  { value: "", label: "All Statuses" },
  { value: "DRAFT", label: "Draft" },
  { value: "PENDING_APPROVAL", label: "Pending Approval" },
  { value: "APPROVED", label: "Approved" },
  { value: "SENT", label: "Sent" },
  { value: "CONFIRMED", label: "Confirmed" },
  { value: "PARTIALLY_RECEIVED", label: "Partially Received" },
  { value: "RECEIVED", label: "Received" },
  { value: "CANCELLED", label: "Cancelled" },
  { value: "CLOSED", label: "Closed" },
];

interface VendorLowStock {
  id: string;
  name: string;
  lowStockCount: number;
  hasDraftPO: boolean;
}

export default function PurchaseOrdersPage() {
  const [orders, setOrders] = useState<any[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [genResult, setGenResult] = useState<string | null>(null);

  // Filter state
  const [search, setSearch] = useState("");
  const [debouncedSearch, setDebouncedSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState("");
  const [dateFrom, setDateFrom] = useState("");
  const [dateTo, setDateTo] = useState("");

  // Vendor selection dialog state
  const [showVendorDialog, setShowVendorDialog] = useState(false);
  const [vendorOptions, setVendorOptions] = useState<VendorLowStock[]>([]);
  const [vendorOptionsLoading, setVendorOptionsLoading] = useState(false);
  const [selectedVendorIds, setSelectedVendorIds] = useState<Set<string>>(new Set());
  const [selectAll, setSelectAll] = useState(true);

  // Debounce search input -- 400ms delay
  const debounceRef = useRef<NodeJS.Timeout | null>(null);
  useEffect(() => {
    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(() => {
      setDebouncedSearch(search);
      setPage(1);
    }, 400);
    return () => {
      if (debounceRef.current) clearTimeout(debounceRef.current);
    };
  }, [search]);

  // Reset to page 1 when filters change
  useEffect(() => {
    setPage(1);
  }, [statusFilter, dateFrom, dateTo]);

  const buildQueryString = useCallback(
    (p: number) => {
      const params = new URLSearchParams();
      params.set("page", String(p));
      params.set("limit", "20");
      if (debouncedSearch) params.set("search", debouncedSearch);
      if (statusFilter) params.set("status", statusFilter);
      if (dateFrom) params.set("dateFrom", dateFrom);
      if (dateTo) params.set("dateTo", dateTo);
      return params.toString();
    },
    [debouncedSearch, statusFilter, dateFrom, dateTo]
  );

  const loadOrders = useCallback(
    async (p: number) => {
      setLoading(true);
      try {
        const res = await fetch(`/api/po?${buildQueryString(p)}`);
        const data = await res.json();
        setOrders(data.orders || []);
        setTotal(data.total || 0);
        setTotalPages(data.totalPages || 1);
      } catch (err) {
        console.error("Failed to load POs:", err);
      } finally {
        setLoading(false);
      }
    },
    [buildQueryString]
  );

  useEffect(() => {
    loadOrders(page);
  }, [page, loadOrders]);

  // --- Open vendor selection dialog ---
  const openAutoGenerateDialog = async () => {
    setShowVendorDialog(true);
    setVendorOptionsLoading(true);
    setSelectedVendorIds(new Set());
    setSelectAll(true);
    try {
      const res = await fetch("/api/po/auto-generate");
      const data = await res.json();
      setVendorOptions(data.vendors || []);
    } catch {
      setVendorOptions([]);
    } finally {
      setVendorOptionsLoading(false);
    }
  };

  const toggleVendor = (vendorId: string) => {
    setSelectAll(false);
    setSelectedVendorIds((prev) => {
      const next = new Set(prev);
      if (next.has(vendorId)) {
        next.delete(vendorId);
      } else {
        next.add(vendorId);
      }
      return next;
    });
  };

  const handleToggleAll = () => {
    if (selectAll) {
      // Deselect all
      setSelectAll(false);
      setSelectedVendorIds(new Set());
    } else {
      // Select all
      setSelectAll(true);
      setSelectedVendorIds(new Set());
    }
  };

  // --- Auto-generate POs (with optional vendor filter) ---
  const handleAutoGenerate = async () => {
    setGenerating(true);
    setGenResult(null);
    setShowVendorDialog(false);
    try {
      // If selectAll is false and we have specific vendor IDs, send them
      const body: any = {};
      if (!selectAll && selectedVendorIds.size > 0) {
        body.vendorIds = Array.from(selectedVendorIds);
      }

      const res = await fetch("/api/po/auto-generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      const data = await res.json();
      setGenResult(data.message);
      loadOrders(1);
      setPage(1);
    } catch {
      setGenResult("Failed to auto-generate POs");
    } finally {
      setGenerating(false);
    }
  };

  // CSV Export -- applies the same active filters
  const handleExportCsv = () => {
    const params = new URLSearchParams();
    if (debouncedSearch) params.set("search", debouncedSearch);
    if (statusFilter) params.set("status", statusFilter);
    if (dateFrom) params.set("dateFrom", dateFrom);
    if (dateTo) params.set("dateTo", dateTo);
    const qs = params.toString();
    window.open(`/api/po/export${qs ? `?${qs}` : ""}`, "_blank");
  };

  const hasActiveFilters = debouncedSearch || statusFilter || dateFrom || dateTo;

  const clearFilters = () => {
    setSearch("");
    setDebouncedSearch("");
    setStatusFilter("");
    setDateFrom("");
    setDateTo("");
    setPage(1);
  };

  // Count eligible vendors (not already with DRAFT PO)
  const eligibleVendors = vendorOptions.filter((v) => !v.hasDraftPO);
  const canGenerate = selectAll
    ? eligibleVendors.length > 0
    : selectedVendorIds.size > 0 && Array.from(selectedVendorIds).some(
        (id) => !vendorOptions.find((v) => v.id === id)?.hasDraftPO
      );

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Purchase Orders</h1>
          <p className="text-muted-foreground">
            {total > 0 ? `${total} purchase orders` : "Create and manage purchase orders"}
          </p>
        </div>
        <div className="flex gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={handleExportCsv}
            title="Export filtered results as CSV"
          >
            <Download className="mr-2 h-4 w-4" />
            Export CSV
          </Button>
          {/* Manual PO creation */}
          <Link href="/po/new">
            <Button size="sm">
              <Plus className="mr-2 h-4 w-4" />
              New PO
            </Button>
          </Link>
          <Button
            variant="outline"
            size="sm"
            onClick={openAutoGenerateDialog}
            disabled={generating}
          >
            <Zap className="mr-2 h-4 w-4" />
            {generating ? "Generating..." : "Auto-Generate POs"}
          </Button>
        </div>
      </div>

      {/* Search and filter bar */}
      <div className="flex flex-wrap items-end gap-3">
        {/* Search input with debounce */}
        <div className="relative flex-1 min-w-[200px] max-w-sm">
          <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
          <Input
            placeholder="Search PO number or vendor..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="pl-9 h-9"
          />
        </div>

        {/* Status filter -- native select styled to match theme */}
        <div className="flex flex-col gap-1">
          <label className="text-xs text-muted-foreground font-medium">Status</label>
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="h-9 rounded-md border border-input bg-background px-3 text-sm ring-offset-background focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
          >
            {PO_STATUSES.map((s) => (
              <option key={s.value} value={s.value}>
                {s.label}
              </option>
            ))}
          </select>
        </div>

        {/* Date from */}
        <div className="flex flex-col gap-1">
          <label className="text-xs text-muted-foreground font-medium">From</label>
          <input
            type="date"
            value={dateFrom}
            onChange={(e) => setDateFrom(e.target.value)}
            className="h-9 rounded-md border border-input bg-background px-3 text-sm ring-offset-background focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
          />
        </div>

        {/* Date to */}
        <div className="flex flex-col gap-1">
          <label className="text-xs text-muted-foreground font-medium">To</label>
          <input
            type="date"
            value={dateTo}
            onChange={(e) => setDateTo(e.target.value)}
            className="h-9 rounded-md border border-input bg-background px-3 text-sm ring-offset-background focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
          />
        </div>

        {/* Clear filters button -- only show when filters active */}
        {hasActiveFilters && (
          <Button variant="ghost" size="sm" onClick={clearFilters} className="h-9">
            <X className="mr-1 h-4 w-4" />
            Clear
          </Button>
        )}
      </div>

      {genResult && (
        <div className={`rounded-lg px-4 py-3 text-sm ${genResult.includes("Failed") ? "bg-red-50 text-red-700" : "bg-green-50 text-green-700"}`}>
          {genResult}
        </div>
      )}

      <Card>
        <CardContent className="p-0">
          {loading && orders.length === 0 ? (
            <div className="flex items-center justify-center py-16 text-muted-foreground">
              Loading purchase orders...
            </div>
          ) : orders.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-16">
              <div className="flex h-16 w-16 items-center justify-center rounded-full bg-muted">
                <FileText className="h-8 w-8 text-muted-foreground" />
              </div>
              <h3 className="mt-4 text-lg font-semibold">
                {hasActiveFilters ? "No matching purchase orders" : "No purchase orders"}
              </h3>
              <p className="mt-2 text-sm text-muted-foreground text-center max-w-sm">
                {hasActiveFilters
                  ? "Try adjusting your search or filters."
                  : 'Click "Auto-Generate POs" to create purchase orders for all items below their reorder point.'}
              </p>
              {hasActiveFilters ? (
                <Button size="sm" variant="outline" className="mt-4" onClick={clearFilters}>
                  Clear Filters
                </Button>
              ) : (
                <Button
                  size="sm"
                  className="mt-4"
                  onClick={openAutoGenerateDialog}
                  disabled={generating}
                >
                  <Zap className="mr-2 h-4 w-4" />
                  Auto-Generate POs
                </Button>
              )}
            </div>
          ) : (
            <>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>PO Number</TableHead>
                    <TableHead>Vendor</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead className="text-center">Items</TableHead>
                    <TableHead className="text-right">Total</TableHead>
                    <TableHead>Created</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {orders.map((po) => (
                    <TableRow key={po.id} className="cursor-pointer hover:bg-muted/50">
                      <TableCell>
                        <Link href={`/po/${po.id}`} className="font-mono text-sm font-medium text-blue-600 hover:underline">
                          {po.poNumber}
                        </Link>
                      </TableCell>
                      <TableCell className="font-medium">
                        {po.vendor?.name || "\u2014"}
                      </TableCell>
                      <TableCell>
                        <Badge className={statusColors[po.status] || "bg-gray-100"}>
                          {po.status.replace(/_/g, " ")}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-center">
                        {po._count?.lineItems || 0}
                      </TableCell>
                      <TableCell className="text-right font-medium">
                        ${Number(po.total).toFixed(2)}
                      </TableCell>
                      <TableCell className="text-sm text-muted-foreground">
                        {new Date(po.createdAt).toLocaleDateString()}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>

              {totalPages > 1 && (
                <div className="flex items-center justify-between border-t px-4 py-3">
                  <p className="text-sm text-muted-foreground">
                    Page {page} of {totalPages}
                  </p>
                  <div className="flex gap-2">
                    <Button variant="outline" size="sm" onClick={() => setPage(Math.max(1, page - 1))} disabled={page <= 1}>
                      <ChevronLeft className="h-4 w-4" /> Previous
                    </Button>
                    <Button variant="outline" size="sm" onClick={() => setPage(Math.min(totalPages, page + 1))} disabled={page >= totalPages}>
                      Next <ChevronRight className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
              )}
            </>
          )}
        </CardContent>
      </Card>

      {/* Vendor Selection Dialog for Auto-Generate */}
      {showVendorDialog && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
          <Card className="mx-4 w-full max-w-lg max-h-[80vh] flex flex-col">
            <div className="p-6 pb-3 border-b">
              <h2 className="text-lg font-semibold flex items-center gap-2">
                <Zap className="h-5 w-5" />
                Auto-Generate Purchase Orders
              </h2>
              <p className="text-sm text-muted-foreground mt-1">
                Select which vendors to generate POs for. Only items below their reorder point will be included.
              </p>
            </div>

            <div className="flex-1 overflow-y-auto p-6 pt-3">
              {vendorOptionsLoading ? (
                <div className="flex items-center gap-2 py-8 justify-center text-muted-foreground">
                  <Loader2 className="h-4 w-4 animate-spin" />
                  Loading vendor data...
                </div>
              ) : vendorOptions.length === 0 ? (
                <div className="py-8 text-center text-muted-foreground">
                  No vendors with low-stock items found.
                </div>
              ) : (
                <div className="space-y-2">
                  {/* All Vendors toggle */}
                  <label className="flex items-center gap-3 p-3 rounded-md border cursor-pointer hover:bg-muted/50 transition-colors">
                    <input
                      type="checkbox"
                      checked={selectAll}
                      onChange={handleToggleAll}
                      className="h-4 w-4 rounded border-gray-300"
                    />
                    <div className="flex-1">
                      <span className="font-medium">All Vendors</span>
                      <span className="ml-2 text-sm text-muted-foreground">
                        ({eligibleVendors.length} vendors, {vendorOptions.reduce((s, v) => s + v.lowStockCount, 0)} low-stock items)
                      </span>
                    </div>
                  </label>

                  <div className="border-t my-2" />

                  {/* Individual vendors */}
                  {vendorOptions.map((vendor) => (
                    <label
                      key={vendor.id}
                      className={`flex items-center gap-3 p-3 rounded-md border cursor-pointer hover:bg-muted/50 transition-colors ${
                        vendor.hasDraftPO ? "opacity-50" : ""
                      }`}
                    >
                      <input
                        type="checkbox"
                        checked={selectAll || selectedVendorIds.has(vendor.id)}
                        disabled={vendor.hasDraftPO || selectAll}
                        onChange={() => toggleVendor(vendor.id)}
                        className="h-4 w-4 rounded border-gray-300"
                      />
                      <div className="flex-1">
                        <span className="font-medium">{vendor.name}</span>
                        <span className="ml-2 text-sm text-muted-foreground">
                          {vendor.lowStockCount} low-stock {vendor.lowStockCount === 1 ? "item" : "items"}
                        </span>
                        {vendor.hasDraftPO && (
                          <Badge variant="secondary" className="ml-2 text-xs">
                            Has Draft PO
                          </Badge>
                        )}
                      </div>
                    </label>
                  ))}
                </div>
              )}
            </div>

            <div className="flex justify-end gap-2 p-6 pt-3 border-t">
              <Button
                variant="outline"
                size="sm"
                onClick={() => setShowVendorDialog(false)}
              >
                Cancel
              </Button>
              <Button
                size="sm"
                onClick={handleAutoGenerate}
                disabled={!canGenerate || generating}
              >
                <Zap className="mr-2 h-4 w-4" />
                {generating ? "Generating..." : "Generate POs"}
              </Button>
            </div>
          </Card>
        </div>
      )}
    </div>
  );
}
